# Generated by Django 2.2 on 2019-04-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytasks',
            name='employee',
            field=models.CharField(choices=[('Денис', 'Денис'), ('Владислав', 'Владислав'), ('Сервис', 'Сервис')], default='Сервис', max_length=10),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='phone',
            field=models.CharField(default='-', max_length=60, unique=True),
        ),
    ]
