# Generated by Django 2.2 on 2019-04-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0002_auto_20190409_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytasks',
            name='cashsumm',
            field=models.IntegerField(default=0, verbose_name='Сумма денег'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='contact_name',
            field=models.CharField(default='-', max_length=20, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='employee',
            field=models.CharField(choices=[('Денис', 'Денис'), ('Владислав', 'Владислав'), ('Сервис', 'Сервис')], default='Сервис', max_length=10, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='get_set',
            field=models.CharField(choices=[('Забрать', 'Забрать'), ('Отдать', 'Отдать')], default='Забрать', max_length=7, verbose_name='Отдать\\забрать'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='payment_method',
            field=models.CharField(choices=[('Нал', 'Нал'), ('Безнал', 'Безнал'), ('Без оплаты', 'Без оплаты')], default='Без оплаты', max_length=11, verbose_name='Нал\\Безнал'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='phone',
            field=models.CharField(default='-', max_length=60, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='process',
            field=models.CharField(choices=[('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено'), ('Первый контакт', 'Первый контакт')], default='Первый контакт', max_length=15, verbose_name='Статус исполнения'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='replace',
            field=models.CharField(default='без подменки', max_length=50, verbose_name='Подменка'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='working_time',
            field=models.CharField(default='-', max_length=50, verbose_name='Рабочее время'),
        ),
    ]
