# Generated by Django 2.2 on 2019-04-10 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0003_auto_20190410_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytasks',
            name='cashsumm',
            field=models.IntegerField(default=0, help_text='Сумма денег которую надо получить от клиента, если оплата не по безналу', verbose_name='Сумма денег'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='contact_name',
            field=models.CharField(default='-', help_text='Имя контактного лица', max_length=20, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата регистрации задачи'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='description',
            field=models.CharField(help_text='Описание - например адрес', max_length=300, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='employee',
            field=models.CharField(choices=[('Денис', 'Денис'), ('Владислав', 'Владислав'), ('Сервис', 'Сервис')], default='Сервис', help_text='Исполнитель данной задачи. Курьер, либо работа не требует доставки', max_length=10, verbose_name='Ответственный'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='id',
            field=models.AutoField(help_text='Уникальное ID для каждой задачи', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='payment_method',
            field=models.CharField(choices=[('Нал', 'Нал'), ('Безнал', 'Безнал'), ('Без оплаты', 'Без оплаты')], default='Без оплаты', help_text='Метод оплаты. Наличный расчет, безналичный либо оплата не требуется', max_length=11, verbose_name='Нал\\Безнал'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='phone',
            field=models.CharField(default='-', help_text='Контактный номер клиента; Уникален и не может повторяться', max_length=60, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='process',
            field=models.CharField(choices=[('Выполнено', 'Выполнено'), ('Не выполнено', 'Не выполнено'), ('Первый контакт', 'Первый контакт')], default='Первый контакт', help_text='Выполнено|Не выполнено|Первый контакт', max_length=15, verbose_name='Статус исполнения'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='replace',
            field=models.CharField(default='без подменки', help_text='Модель подменного картриджа, если он необходим', max_length=50, verbose_name='Подменка'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='working_time',
            field=models.CharField(default='-', help_text='Время работы клиента', max_length=50, verbose_name='Рабочее время'),
        ),
    ]
