# Generated by Django 2.2 on 2019-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_auto_20190410_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytasks',
            name='cashsumm',
            field=models.IntegerField(help_text='Сумма денег которую надо получить от клиента, если оплата не по безналу', verbose_name='Сумма денег'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='contact_name',
            field=models.CharField(help_text='Имя контактного лица', max_length=20, verbose_name='Контактное лицо'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='phone',
            field=models.CharField(help_text='Контактный номер клиента; Уникален и не может повторяться', max_length=60, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='daytasks',
            name='working_time',
            field=models.CharField(help_text='Время работы клиента', max_length=50, verbose_name='Рабочее время'),
        ),
    ]
