# Generated by Django 2.2 on 2019-04-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0006_auto_20190410_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytasks',
            name='working_time',
        ),
        migrations.AddField(
            model_name='daytasks',
            name='working_time_1',
            field=models.CharField(default=0, help_text='Со скольки', max_length=15, verbose_name='Рабочее время. С:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daytasks',
            name='working_time_2',
            field=models.CharField(default=0, help_text='До скольки', max_length=15, verbose_name='Рабочее время. ДО:'),
            preserve_default=False,
        ),
    ]
