# Generated by Django 2.2 on 2019-04-12 17:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0007_auto_20190410_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=20, verbose_name='Кодовое название')),
                ('simple_name', models.CharField(blank=True, max_length=200, verbose_name='Бытовое название')),
                ('resourse', models.IntegerField()),
                ('part', models.CharField(choices=[('CART', 'картридж'), ('DRUM', 'драм'), ('TONER', 'туба')], max_length=10, verbose_name='Тип')),
                ('color', models.CharField(choices=[('CYAN', 'cyan'), ('MAGENTA', 'magenta'), ('YELLOW', 'yellow'), ('BLACK', 'black')], max_length=10, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('dateoflisted', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации клиента')),
                ('name', models.CharField(max_length=50, verbose_name='Название или имя')),
                ('phone', models.CharField(max_length=300, verbose_name='Контакты')),
                ('adress', models.CharField(max_length=300, verbose_name='Адрес')),
                ('organisation', models.CharField(choices=[('PH', 'физическое_лицо'), ('CO', 'компания'), ('NO', 'неизвестно')], default='NO', max_length=20, verbose_name='Физическое лицо или организация')),
                ('commentary', models.CharField(max_length=300, verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20, verbose_name='Имя')),
                ('middlename', models.CharField(max_length=20, verbose_name='Отчество')),
                ('lastname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('function', models.CharField(choices=[('CO', 'курьер'), ('MA', 'менеджер'), ('EN', 'инженер')], max_length=10, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('compatibility', models.ManyToManyField(to='logistic.Cartridge')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(help_text='Уникальное ID для каждой задачи', primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(choices=[('DONE', 'Выполнено'), ('NOT_D', 'Не выполнено'), ('FIRST', 'Первый контакт'), ('ERROR', 'Срыв процесса')], default='FIRST', help_text='Выполнено|Не выполнено|Первый контакт', max_length=15, verbose_name='Статус исполнения')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('working_time_1', models.CharField(help_text='Со скольки', max_length=15, verbose_name='Рабочее время. С:')),
                ('working_time_2', models.CharField(help_text='До скольки', max_length=15, verbose_name='Рабочее время. ДО:')),
                ('cashsumm', models.IntegerField(help_text='Сумма денег которую надо получить от клиента, если оплата не по безналу', verbose_name='Сумма денег')),
                ('get_set', models.CharField(choices=[('GET', 'Забрать'), ('SET', 'Отдать'), ('NO', 'Самовывоз')], default='NO', help_text='Отдать клиенту, забрать у клиента либо ничего не делать', max_length=7, verbose_name='Отдать\\забрать')),
                ('replace', models.CharField(default='без подменки', help_text='Модель подменного картриджа, если он необходим', max_length=50, verbose_name='Подменка')),
                ('payment_method', models.CharField(choices=[('Нал', 'Нал'), ('Безнал', 'Безнал'), ('Без оплаты', 'Без оплаты')], default='Без оплаты', help_text='Метод оплаты. Наличный расчет, безналичный либо оплата не требуется', max_length=11, verbose_name='Нал\\Безнал')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.Client')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.Employee')),
            ],
        ),
        migrations.DeleteModel(
            name='DayTasks',
        ),
    ]
