# Generated by Django 2.2 on 2019-04-13 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0008_auto_20190412_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='replace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.Cartridge'),
        ),
    ]
