# Generated by Django 2.2 on 2019-04-13 17:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0009_auto_20190413_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('opc', models.BooleanField(default=False, verbose_name='фотобарабан')),
                ('pcr', models.BooleanField(default=False, verbose_name='ролик заряда')),
                ('mag', models.BooleanField(default=False, verbose_name='магнит')),
                ('doc', models.BooleanField(default=False, verbose_name='дозирующее')),
                ('wip', models.BooleanField(default=False, verbose_name='ракель')),
                ('chip', models.BooleanField(default=False, verbose_name='чип')),
                ('fill', models.BooleanField(default=False, verbose_name='заправка')),
                ('new', models.BooleanField(default=False, verbose_name='надо новый')),
                ('trash', models.BooleanField(default=False, verbose_name='списать')),
                ('comment', models.CharField(max_length=50, verbose_name='коментарий')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.Cartridge')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.Task')),
            ],
        ),
    ]
