# Generated by Django 2.2 on 2019-04-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0010_servicetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='comment',
            field=models.CharField(default=' ', max_length=50, verbose_name='коментарий'),
        ),
    ]
