# Generated by Django 2.2 on 2019-04-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0011_auto_20190413_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetask',
            name='comment',
            field=models.CharField(blank=True, default=' ', max_length=50, verbose_name='коментарий'),
        ),
    ]
